---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codejourney-db
  namespace: dev-testing
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAA3Nr2OlHdQPIdyD/ybpMzH+H1bCw8BzwGfChx3laTMTpv9Bqbe1nRfXzy87GyXMVf4oSrSAlUwPveIhgLK42NYBnr2wbvxkkGG22+zgDsCpFTujhx49WEg/0FryUhctFju385Q8KPb6h6sEFaYGN4+HmKYLZMtm5HYRQDbOxLGQzj7p2OfFF6TiTSaZXnf+DGqzow3mw4T7KyYb/BnykW4CZEOtf1pDMfkNU3HhPZHGxnLS6yu4oL8wNRi7y0UqTGNsUlU49OoxmzWNSr6JRhr7nNYR2Va6gehRi2/gKoftluS5ohdsTmGna4iI1IPz81I9cQ+aJ7NAou05XTNhXo9gZE1A0UJ4G1I2X+mMwY/DvW/MJ8nlUrgZMM9g/bBP4sqOjbvxMSTwPFW8VXhtxfHRfSYz5WZUSOUUQkXM2D9aHO7MM7/TwE17+J9uq/+tqS46wI8OJhmxnL2oufHSc2se+Zhlr3ocNnUZYivIGqFTyZIy7NZ8TgSjnxVBbkF6JaDqKh6ssrGjIKhHwe3GXo4e9grUBtdJCqyiZ7Ol9V2s51dD7ldTwaUunn0TGrk4GMFnzYMmJtWDG578CpykzJfsSdwkIDfD2cSsjMsOeNQ8FEmDalO2a9nqc0e4qFMkYc73WHd+8U8edkWjaRT17UL84N7q8fjnsDeJYlLdFBSGnoR4BDtJ9OtqMNTzlQ6p8qC1O4qveD4oNcRVzWoPpJjEux+NKjItNZ1BX+5U2nQA==
    POSTGRES_USER: AgBPsAFiOfP9SRWQhcYDzkIjLwmMpLkEiX3xNDniCQeehdr+KjQt14FvXUS1wPisTjEgkVTBSalZmNminHYTJg37dld/x9wUtP2Uaq5nfCeekxol5YnJJ36NfVTRIuzwGAyWn2KpxYARuQkMnKH7grgThFaa+tzSblOd/e+k6bG8niDLBsMN0MbIh33EgYvgHcGX+r/B/k2ab3rno5Pf8pWXToGeuVkPqlP5MET8eG6BfU6w8sQXA1RHO84b5CFDbEJUJmVv+gtpWswBX7FbQaImiY0rFdqgxiBXVQ5c6p7FvEukFGF5E+k3/sUHOq2xzN08xAj7xHzTYl1bBvECQwdIfcT1EN295i6+KyCjmt0wyoRGoG33WLhs+IQQlpk/8kW6uZA/PMt8jSfwR0LA3LZ9Arm1bzHP7GKOX3eBqCqjSbZXq5+R4m+a/pXseX4ClviaZGrDKUqNGCLTy/+1iA1+LIFp2U4L58zfA8xlK/4N7aiCPlrRokSe8dCG2IG/34Uf0ETi74/W7zg3ktNehJSs0xdr9S2yYHAzh5wJxVHRr0qXu69pzOcyUgJcPsdk2HJ+AnJklVkF1YBsVvdUeKuxT/o0yW6y/L0ocBVkhxlV5RL74kv+6Z/5/T2pR2tC5x6rGSiAEB028fJXvdrq79AoOBb25G1E1QWUNIcT18WydHOZNodyD1IkyLxzxTsMl9RR3GTCIWHYKg2pbA==
  template:
    metadata:
      name: codejourney-db
      namespace: dev-testing
