apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codejourney
  namespace: dev-testing
  annotations:
    tailscale.com/funnel: "false"    # accessible only within your tailnet
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: codejourney
      port:
        number: 80
  tls:
    - hosts:
        - codejourney                # becomes codejourney.tail9d71dd.ts.net
